project:
  type: book

book:
  title: "Handbook on Statistical Disclosure Control"
  subtitle: "Second Edition"
  author: 
    - name: Anco Hundepool
    - name: Josep Domingo-Ferrer
    - name: Luisa Franconi
    - name: Sarah Giessing
    - name: Rainer Lenz
    - name: Jane Naylor
    - name: Eric Schulte Nordholt
    - name: Giovanni Seri
    - name: Peter-Paul De Wolf
    - name: Reinhard Tent
    - name: Andrzej MÅ‚odak
    - name: Johannes Gussenbauer
  date: today
  date-format: YYYY, MMMM DD
  repo-url: https://github.com/julienjamme/handbook_sdc_from_doc_to_md
  chapters:
    - index.qmd
    - 01-Introduction.qmd
    - 02-regulations.qmd
    - 03-microdata.qmd
    - 04-magnitude-tabular-data.qmd
    - 05-frequency-tables.qmd
    - 06-remote-access-issues.qmd
    - 07-glossary.qmd
    # - 08-final-index.qmd
  page-navigation: true

bibliography: references.bib


format:
  html:
    theme: 
      - cosmo
      - custom.scss
    reference-location: margin
    citation-location: margin
    cap-location: margin
    code-link: true
  # pdf:
  #   # pdf-engine: xelatex
  #   # fig-pos: 'h'
  #   latex-tinytex: false
  #   documentclass: scrbook
  #   classoption: ["oneside", "open=any"]
  #   papersize: a4
  #   toc: true
  #   keep-tex: true
  #   geometry:
  #     - left=3cm
  #     - right=3cm
  #     # - textwidth=4.5in
  #     # - marginparsep=.25in
  #     # - marginparwidth=2.25in
  #   template-partials:
  #     - "before-body.tex"
  #     - "_titlepage.tex" 
  #   include-in-header: 
  #     text: |
  #       \usepackage[english]{babel}
  #       \usepackage[utf8]{inputenc}
  #       \usepackage{float}
  #       \usepackage{multirow}
  #       \usepackage{hyperref}
  #       \usepackage{setspace}
  #       \PassOptionsToPackage{hyphens}{url}\usepackage{hyperref}
  #       \makeatletter
  #       \renewenvironment{table}
  #         {\@float{table}[H]}
  #         {\end@float}
  #       \makeatother
  #       \counterwithout{footnote}{chapter}
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

execute:
  freeze: auto
